name: NuxSigns
main: com.bukkit.N4th4.NuxSigns.NuxSigns
version: 1.2
depend:
    - PermissionsEx
commands:
    sign:
        description: All of the NuxSigns commands
        usage: Command unrecognised by NuxSigns.